"""Regenerate docs/adr/INDEX.md from ADR frontmatter.

Run manually from the repo root: python3 -m scripts.adr.generate_index
Run automatically by .githooks/pre-commit when ADR files are staged.

Stdlib-only by design (ADR 007): ADR frontmatter is a flat key/value block, so a
small line parser suffices and the repo needs no Python project (or PyYAML) at its
root. That parser lives in scripts.frontmatter, shared with the manifest validator
so the two cannot disagree on the same input (ADR 011).
"""

import re
import sys
from pathlib import Path

from scripts.frontmatter import parse_frontmatter

ADR_DIR = Path("docs/adr")
ADR_INDEX_FILENAME = "INDEX.md"

STATUSES = ("Accepted", "Archived", "Superseded")

# Kept out of the index an agent loads by default: Superseded because a later ADR
# replaced it, Archived because something other than a reader carries it — a comment
# wherever a breach would be authored, or the archived-decisions check in
# phx:writing-adrs. Both keep their full text in the repo, and an Archived decision
# is as binding as an Accepted one.
HIDDEN_STATUSES = ("Archived", "Superseded")

# Frontmatter each status requires and the others refuse, so a status changed without
# its companion field fails here rather than leaving stale metadata behind.
STATUS_FIELDS = {"Archived": "archived-because", "Superseded": "superseded-by"}

# The revisit trigger and the ADR that spent it. These pair with each other rather than
# with a status: either sits with any status, and a discharge names something to spend,
# so it cannot stand alone.
REVISIT_WHEN_FIELD = "revisit-when"
REVISIT_DISCHARGED_BY_FIELD = "revisit-discharged-by"

INDEX_HEADER = (
    "<!-- Auto-generated by `python3 -m scripts.adr.generate_index` — do not edit manually. -->\n"
    "\n"
    "# ADR Index\n"
)
TABLE_HEADER = (
    "| # | Status | Title | Tags | Summary | Revisit |\n"
    "|---|--------|-------|------|---------|---------|\n"
)

# An empty table reads as a file that was truncated. Say so instead.
EMPTY_NOTE = "_No decisions are recorded yet._\n"

RE_ADR_FILENAME = re.compile(r"^\d+-.*\.md$")
RE_FILE_NUMBER = re.compile(r"^(\d+)")
RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
RE_H1_TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
RE_NUMBER_PREFIX = re.compile(r"^\d+:\s*")


def parse_adr(content: str) -> tuple[dict, str, list[str]]:
    """Return (frontmatter, title, problems) for one ADR document.

    Every rule a document must satisfy to be an ADR is checked here rather than split
    with the caller, which then only decides what to do with a file that has problems.
    A caller cannot hold a different view of what makes an ADR valid than the function
    that parses one.

    `problems` is empty only when both returned values are usable; on any problem the
    fields and title carry whatever could still be read, for an error message to name.
    """
    match = RE_FRONTMATTER.match(content)
    if not match:
        return {}, "", ["has no frontmatter block"]

    fields, problems = parse_frontmatter(match.group(1))

    title_match = RE_H1_TITLE.search(match.group(2))
    if title_match:
        title = RE_NUMBER_PREFIX.sub("", title_match.group(1).strip())
    else:
        title = ""
        problems.append("has no level-one title heading")

    status = fields.get("status")
    if status not in STATUSES:
        problems.append(f"has status {status!r}; expected one of {', '.join(STATUSES)}")
    for owner, field in STATUS_FIELDS.items():
        if status == owner and not fields.get(field):
            problems.append(f"is {owner} but declares no `{field}`")
        elif status != owner and fields.get(field):
            problems.append(f"declares `{field}` but its status is {status!r}, not {owner}")

    if fields.get(REVISIT_DISCHARGED_BY_FIELD) and not fields.get(REVISIT_WHEN_FIELD):
        problems.append(
            f"declares `{REVISIT_DISCHARGED_BY_FIELD}` but no `{REVISIT_WHEN_FIELD}` to spend"
        )
    return fields, title, problems


def cell(value: str | list[str]) -> str:
    """Render a frontmatter value for a Markdown table cell, escaping pipes."""
    if isinstance(value, list):
        value = ", ".join(value)
    return value.replace("|", "\\|")


def generate(adr_dir: Path = ADR_DIR) -> int:
    """Regenerate INDEX.md from ADR frontmatter. Return 0 on success, 1 on error.

    `adr_dir` is a parameter so tests can point at a fixture directory. Defaulting
    it to a path relative to the working directory is what lets every caller run
    this from the repo root without arguments.
    """
    index_file = adr_dir / ADR_INDEX_FILENAME

    rows = []
    has_errors = False
    for path in sorted(adr_dir.iterdir()):
        # Dot-files are editor and tooling debris, not documents anyone filed here.
        if path.name.startswith(".") or path.name == ADR_INDEX_FILENAME:
            continue
        # The directory holds ADRs and the index, nothing else, so an unrecognised
        # name is either a document misfiled here or an ADR named wrongly — and the
        # second would drop out of the index silently.
        if not RE_ADR_FILENAME.match(path.name):
            print(
                f"Error: {path.name} is neither an ADR nor {ADR_INDEX_FILENAME}; "
                f"rename it NNN-slug.md or move it elsewhere under docs/",
                file=sys.stderr,
            )
            has_errors = True
            continue

        fields, title, problems = parse_adr(path.read_text(encoding="utf-8"))
        if problems:
            for problem in problems:
                print(f"Error: {path.name} {problem}", file=sys.stderr)
            has_errors = True
            continue
        if fields["status"] in HIDDEN_STATUSES:
            continue

        # A discharged trigger leaves the index the way a Superseded ADR does: the
        # condition is spent, so carrying it costs every reader context for something
        # nobody can act on. The pair stays in the ADR's own frontmatter as the record.
        revisit = (
            "" if fields.get(REVISIT_DISCHARGED_BY_FIELD) else fields.get(REVISIT_WHEN_FIELD, "")
        )

        # RE_ADR_FILENAME already required a leading number, so this always matches.
        number = RE_FILE_NUMBER.match(path.name).group(1)
        rows.append(
            f"| [{number}]({path.name}) | {cell(fields['status'])} "
            f"| {cell(title)} | {cell(fields.get('tags', []))} "
            f"| {cell(fields.get('summary', ''))} | {cell(revisit)} |\n"
        )

    if has_errors:
        print("Fix the errors above before committing.", file=sys.stderr)
        return 1

    body = TABLE_HEADER + "".join(rows) if rows else EMPTY_NOTE
    index_file.write_text(f"{INDEX_HEADER}\n{body}", encoding="utf-8")
    print(f"Generated {index_file} ({len(rows)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(generate())
