"""Regenerate docs/adr/INDEX.md from ADR frontmatter.

Run manually from the repo root: python3 -m scripts.adr.generate_index
Run automatically by .githooks/pre-commit when ADR files are staged.

Stdlib-only by design (ADR 007): ADR frontmatter is a flat key/value block, so a
small line parser suffices and the repo needs no Python project (or PyYAML) at its
root. That parser lives in scripts.frontmatter, shared with the manifest validator
so the two cannot disagree on the same input (ADR 011).
"""

import re
import sys
from pathlib import Path

from scripts.frontmatter import parse_frontmatter

ADR_DIR = Path("docs/adr")

STATUSES = ("Accepted", "Archived", "Superseded")

# Kept out of the index an agent loads by default: Superseded because a later ADR
# replaced it, Archived because the decision stands but isn't worth carrying. Both
# stay in the repo.
HIDDEN_STATUSES = ("Archived", "Superseded")

RE_ADR_FILENAME = re.compile(r"^\d+-.*\.md$")
RE_FILE_NUMBER = re.compile(r"^(\d+)")
RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
RE_H1_TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
RE_NUMBER_PREFIX = re.compile(r"^\d+:\s*")


def parse_adr(content: str):
    """Return (frontmatter, title, problems) for an ADR, or None if either is missing."""
    match = RE_FRONTMATTER.match(content)
    if not match:
        return None
    title_match = RE_H1_TITLE.search(match.group(2))
    if not title_match:
        return None
    title = RE_NUMBER_PREFIX.sub("", title_match.group(1).strip())
    fields, problems = parse_frontmatter(match.group(1))
    return fields, title, problems


def cell(value) -> str:
    """Render a frontmatter value for a Markdown table cell, escaping pipes."""
    if isinstance(value, list):
        value = ", ".join(value)
    return value.replace("|", "\\|")


def generate(adr_dir: Path = ADR_DIR) -> int:
    """Regenerate INDEX.md from ADR frontmatter. Return 0 on success, 1 on error.

    `adr_dir` is a parameter so tests can point at a fixture directory. Defaulting
    it to a path relative to the working directory is what lets every caller run
    this from the repo root without arguments.
    """
    index_file = adr_dir / "INDEX.md"
    files = sorted(f for f in adr_dir.iterdir() if RE_ADR_FILENAME.match(f.name))

    rows = []
    has_errors = False
    for path in files:
        parsed = parse_adr(path.read_text(encoding="utf-8"))
        if not parsed:
            print(
                f"Error: {path.name} is missing frontmatter or a title heading",
                file=sys.stderr,
            )
            has_errors = True
            continue
        fields, title, problems = parsed
        for problem in problems:
            print(f"Error: {path.name} {problem}", file=sys.stderr)
            has_errors = True

        # Checked before the skip below, so a typo excludes nothing silently: an
        # unrecognised status would otherwise land in the index as a literal, and a
        # misspelled hidden one would publish an ADR meant to stay out.
        status = fields.get("status")
        if status not in STATUSES:
            print(
                f"Error: {path.name} has status {status!r}; expected one of "
                f"{', '.join(STATUSES)}",
                file=sys.stderr,
            )
            has_errors = True
            continue
        if status in HIDDEN_STATUSES:
            continue
        # RE_ADR_FILENAME already required a leading number, so this always matches.
        number = RE_FILE_NUMBER.match(path.name).group(1)
        rows.append(
            f"| [{number}]({path.name}) | {cell(fields.get('status', ''))} "
            f"| {cell(title)} | {cell(fields.get('tags', []))} | {cell(fields.get('summary', ''))} |"
        )

    if has_errors:
        print("Fix the errors above before committing.", file=sys.stderr)
        return 1

    output = "\n".join(
        [
            "<!-- Auto-generated by `python3 -m scripts.adr.generate_index` — do not edit manually. -->",
            "",
            "# ADR Index",
            "",
            "| # | Status | Title | Tags | Summary |",
            "|---|--------|-------|------|---------|",
            *rows,
            "",
        ]
    )
    index_file.write_text(output, encoding="utf-8")
    print(f"Generated {index_file} ({len(rows)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(generate())
