#!/usr/bin/env python3
"""Regenerate docs/adr/INDEX.md from ADR frontmatter.

Run manually from the repo root: python3 scripts/adr/generate_index.py
Run automatically by .githooks/pre-commit when ADR files are staged.

Stdlib-only by design: ADR frontmatter is a flat key/value block, so a small
line parser suffices and the repo needs no Python project (or PyYAML) at its root.
"""

import re
import sys
from pathlib import Path

ADR_DIR = Path("docs/adr")
INDEX_FILE = ADR_DIR / "INDEX.md"

RE_ADR_FILENAME = re.compile(r"^\d+-.*\.md$")
RE_FILE_NUMBER = re.compile(r"^(\d+)")
RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
RE_H1_TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
RE_NUMBER_PREFIX = re.compile(r"^\d+:\s*")


def parse_frontmatter(block: str) -> dict:
    """Parse a flat YAML frontmatter block into a dict.

    Handles `key: value` scalars and `key: [a, b, c]` inline lists — the only
    shapes ADR frontmatter uses. List values become list[str]; scalars stay str.
    """
    fields: dict = {}
    for line in block.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            items = [item.strip() for item in value[1:-1].split(",")]
            fields[key] = [item for item in items if item]
        else:
            fields[key] = value
    return fields


def parse_adr(content: str):
    """Return (frontmatter, title) for an ADR, or None if either is missing."""
    match = RE_FRONTMATTER.match(content)
    if not match:
        return None
    title_match = RE_H1_TITLE.search(match.group(2))
    if not title_match:
        return None
    title = RE_NUMBER_PREFIX.sub("", title_match.group(1).strip())
    return parse_frontmatter(match.group(1)), title


def cell(value) -> str:
    """Render a frontmatter value for a Markdown table cell, escaping pipes."""
    if isinstance(value, list):
        value = ", ".join(value)
    return value.replace("|", "\\|")


def generate() -> int:
    """Regenerate INDEX.md from ADR frontmatter. Return 0 on success, 1 on error."""
    files = sorted(f for f in ADR_DIR.iterdir() if RE_ADR_FILENAME.match(f.name))

    rows = []
    has_errors = False
    for path in files:
        parsed = parse_adr(path.read_text(encoding="utf-8"))
        if not parsed:
            print(
                f"Error: {path.name} is missing frontmatter or a title heading",
                file=sys.stderr,
            )
            has_errors = True
            continue
        fields, title = parsed
        if fields.get("status") == "Superseded":
            continue
        number_match = RE_FILE_NUMBER.match(path.name)
        if not number_match:
            print(f"Error: {path.name} has no leading number", file=sys.stderr)
            has_errors = True
            continue
        rows.append(
            f"| [{number_match.group(1)}]({path.name}) | {cell(fields.get('status', ''))} "
            f"| {cell(title)} | {cell(fields.get('tags', []))} | {cell(fields.get('summary', ''))} |"
        )

    if has_errors:
        print("Fix the errors above before committing.", file=sys.stderr)
        return 1

    output = "\n".join(
        [
            "<!-- Auto-generated by scripts/adr/generate_index.py — do not edit manually. -->",
            "",
            "# ADR Index",
            "",
            "| # | Status | Title | Tags | Summary |",
            "|---|--------|-------|------|---------|",
            *rows,
            "",
        ]
    )
    INDEX_FILE.write_text(output, encoding="utf-8")
    print(f"Generated {INDEX_FILE} ({len(rows)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(generate())
