"""Unit tests for generate_index.py.

Stdlib `unittest` rather than pytest, so the suite needs no dependency of its own
(ADR 007). Run from the repo root:

    python3 -m unittest discover -s scripts -t . -p 'test_*.py'

`generate()` takes its directory as an argument, so these tests never chdir into
the repo — the one exception covers default resolution deliberately. Without that,
a test reaching `generate()` would rewrite the real docs/adr/INDEX.md, which the
pre-commit hook then stages.
"""

import contextlib
import io
import tempfile
import unittest
from pathlib import Path

from scripts.adr.generate_index import HIDDEN_STATUSES, cell, generate, parse_adr

HEADER = (
    "<!-- Auto-generated by scripts/adr/generate_index.py — do not edit manually. -->\n"
    "\n"
    "# ADR Index\n"
    "\n"
    "| # | Status | Title | Tags | Summary |\n"
    "|---|--------|-------|------|---------|\n"
)

SENTINEL = "untouched\n"


def adr(status: str = "Accepted", title: str = "1: Do the thing", **fields) -> str:
    """Build an ADR file body with the given frontmatter and title."""
    lines = [f"status: {status}", "date: 2026-08-01", "tags: [alpha, beta]", "summary: A summary."]
    for key, value in fields.items():
        lines = [line for line in lines if not line.startswith(f"{key}:")]
        if value is not None:
            lines.append(f"{key}: {value}")
    return "---\n" + "\n".join(lines) + f"\n---\n\n# {title}\n\nBody.\n"


class AdrDirTestCase(unittest.TestCase):
    """A temp directory standing in for docs/adr, living for the whole test."""

    def setUp(self):
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        self.root = Path(directory.name)

    def write(self, name: str, content: str) -> None:
        """Place a file in the fixture directory."""
        (self.root / name).write_text(content, encoding="utf-8")

    def run_generate(self) -> tuple[int, str]:
        """Run generate() against the fixture, returning its exit code and stderr."""
        stderr = io.StringIO()
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(stderr):
            code = generate(self.root)
        return code, stderr.getvalue()

    def index(self) -> str:
        """Read the generated index."""
        return (self.root / "INDEX.md").read_text(encoding="utf-8")


class ParseAdrTests(unittest.TestCase):
    def test_returns_none_without_frontmatter(self):
        """A file with no frontmatter block cannot yield an index row."""
        self.assertIsNone(parse_adr("# 1: Title\n\nBody.\n"))

    def test_returns_none_without_a_title(self):
        """A file with no level-one heading cannot yield an index row."""
        self.assertIsNone(parse_adr("---\nstatus: Accepted\n---\n\nBody with no heading.\n"))

    def test_strips_the_number_prefix_from_the_title(self):
        """The index column carries the title alone; the number is already its own column."""
        _, title, _ = parse_adr(adr(title="7: Keep repo scripts stdlib-only"))
        self.assertEqual(title, "Keep repo scripts stdlib-only")

    def test_keeps_a_title_that_has_no_number_prefix(self):
        """A title written without a number is left as it stands."""
        _, title, _ = parse_adr(adr(title="Keep repo scripts stdlib-only"))
        self.assertEqual(title, "Keep repo scripts stdlib-only")

    def test_propagates_frontmatter_problems(self):
        """Problems from the shared parser reach the caller rather than being swallowed."""
        content = "---\nstatus: Accepted\nnonsense\n---\n\n# 1: Title\n\nBody.\n"
        _, _, problems = parse_adr(content)
        self.assertEqual(problems, ["is not `key: value`: 'nonsense'"])

    def test_a_horizontal_rule_does_not_extend_the_frontmatter(self):
        """Frontmatter ends at its own closing fence, not at a rule further down."""
        content = "---\nstatus: Accepted\n---\n\n# 1: Title\n\n---\n\nMore body.\n"
        fields, title, problems = parse_adr(content)
        self.assertEqual((fields, title, problems), ({"status": "Accepted"}, "Title", []))

    def test_the_first_heading_wins(self):
        """A later level-one heading cannot displace the ADR's own title."""
        content = "---\nstatus: Accepted\n---\n\n# 1: Real title\n\n# Later heading\n"
        _, title, _ = parse_adr(content)
        self.assertEqual(title, "Real title")


class CellTests(unittest.TestCase):
    def test_joins_a_list_with_commas(self):
        """Tags render as one comma-separated cell."""
        self.assertEqual(cell(["ci", "adr"]), "ci, adr")

    def test_escapes_pipes_in_a_scalar(self):
        """An unescaped pipe would silently split the row into extra columns."""
        self.assertEqual(cell("Use mypy | not ty"), "Use mypy \\| not ty")

    def test_escapes_pipes_inside_a_list(self):
        """Escaping happens after joining, so a pipe in one item is caught too."""
        self.assertEqual(cell(["a|b", "c"]), "a\\|b, c")


ONE_ROW = "| [001](001-first.md) | Accepted | Do the thing | alpha, beta | A summary. |\n"


class GenerateTests(AdrDirTestCase):
    def test_writes_a_row_for_each_accepted_adr(self):
        """The happy path produces the whole file, not merely something containing a row."""
        self.write("001-first.md", adr())
        code, _ = self.run_generate()
        self.assertEqual(code, 0)
        self.assertEqual(self.index(), HEADER + ONE_ROW)

    def test_excludes_hidden_statuses_but_keeps_their_neighbours(self):
        """A hidden ADR leaves the index while an accepted sibling stays in it."""
        for status in HIDDEN_STATUSES:
            with self.subTest(status=status):
                self.write("001-visible.md", adr())
                self.write("002-hidden.md", adr(status=status))
                code, _ = self.run_generate()
                self.assertEqual(code, 0)
                self.assertIn("001-visible.md", self.index())
                self.assertNotIn("002-hidden.md", self.index())

    def test_orders_rows_by_file_number(self):
        """Zero-padded numbers sort as strings, so 009 must precede 010."""
        self.write("010-later.md", adr())
        self.write("009-earlier.md", adr())
        self.run_generate()
        rows = [line for line in self.index().splitlines() if line.startswith("| [")]
        self.assertEqual([row.split("]")[0] for row in rows], ["| [009", "| [010"])

    def test_ignores_files_that_are_not_adrs(self):
        """The index must not list itself, a readme, or an unnumbered note."""
        self.write("001-real.md", adr())
        self.write("INDEX.md", SENTINEL)
        self.write("README.md", "# Readme\n")
        self.write("notes.md", "# Notes\n")
        code, _ = self.run_generate()
        self.assertEqual(code, 0)
        self.assertIn("001-real.md", self.index())
        for ignored in ("INDEX.md", "README.md", "notes.md"):
            self.assertNotIn(f"]({ignored})", self.index())

    def test_writes_an_empty_table_for_an_empty_directory(self):
        """No ADRs still yields a valid table rather than a malformed file."""
        code, _ = self.run_generate()
        self.assertEqual(code, 0)
        self.assertEqual(self.index(), HEADER)

    def test_is_idempotent(self):
        """The CI check diffs this file, so a second run must reproduce it exactly."""
        self.write("001-first.md", adr())
        self.run_generate()
        first = self.index()
        self.run_generate()
        self.assertEqual(self.index(), first)
        self.assertEqual(first, HEADER + ONE_ROW)


class GenerateFailureTests(AdrDirTestCase):
    """On any error the index must be left exactly as it was found."""

    def assert_rejected(self, content: str, *expected: str):
        """Run against one bad ADR and assert the exit code, message, and untouched index."""
        self.write("001-bad.md", content)
        self.write("INDEX.md", SENTINEL)
        code, stderr = self.run_generate()
        self.assertEqual(code, 1)
        for fragment in ("001-bad.md",) + expected:
            self.assertIn(fragment, stderr)
        self.assertEqual(self.index(), SENTINEL)

    def test_rejects_an_unrecognised_status(self):
        """A status outside the vocabulary must not reach the index as a literal."""
        self.assert_rejected(adr(status="Draft"), "'Draft'", "Accepted, Archived, Superseded")

    def test_rejects_a_status_in_the_wrong_case(self):
        """Matching is exact, so `archived` cannot quietly hide an ADR."""
        self.assert_rejected(adr(status="archived"), "'archived'")

    def test_rejects_a_missing_status(self):
        """An ADR with no status has no place in the index either way."""
        self.assert_rejected(adr(status=None), "None")

    def test_rejects_a_wrapped_frontmatter_value(self):
        """The truncation the shared parser catches must fail the run, not shorten a row."""
        content = (
            "---\nstatus: Accepted\nsummary: Something long\n  and its remainder\n"
            "---\n\n# 1: Title\n\nBody.\n"
        )
        self.assert_rejected(content, "continued onto another line")

    def test_rejects_a_file_missing_its_frontmatter(self):
        """A file that cannot be parsed at all is an error, not a silent omission."""
        self.assert_rejected("# 1: Title\n\nBody.\n", "missing frontmatter or a title heading")

    def test_reports_every_bad_file(self):
        """Two broken ADRs produce two errors, so one fix does not reveal the next."""
        self.write("001-bad.md", adr(status="Draft"))
        self.write("002-bad.md", adr(status="Nope"))
        code, stderr = self.run_generate()
        self.assertEqual(code, 1)
        self.assertIn("001-bad.md", stderr)
        self.assertIn("002-bad.md", stderr)


class DefaultDirectoryTests(unittest.TestCase):
    def test_defaults_to_docs_adr_under_the_working_directory(self):
        """Callers run this from the repo root with no arguments; that path must resolve."""
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "docs" / "adr"
            root.mkdir(parents=True)
            (root / "001-first.md").write_text(adr(), encoding="utf-8")
            with contextlib.chdir(directory):
                with contextlib.redirect_stdout(io.StringIO()):
                    code = generate()
            self.assertEqual(code, 0)
            self.assertIn("001-first.md", (root / "INDEX.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
