"""ADR scaffolding, index and scope checks for the writing-adrs skill.

Standard library only, so it runs wherever `python3` does and needs no virtualenv.
The skill runs it as `python3 ${CLAUDE_SKILL_DIR}/adr.py <command>`, the plugin's hooks
reach it through hook.py, and a consumer's CI as `phx-adr`.

    adr.py [--repo-root DIR] new TITLE --summary S (--scope P ... | --no-scope) [--revisit-when R]
    adr.py [--repo-root DIR] index
    adr.py [--repo-root DIR] check
    adr.py [--repo-root DIR] for PATH ...
    adr.py [--repo-root DIR] supersede OLD --by NEW
    adr.py [--repo-root DIR] discharge OLD --by NEW
    adr.py [--repo-root DIR] renumber OLD NEW
    adr.py [--repo-root DIR] reconcile [--write]

The tool acts on the caller's tree, never the one it ships in. Every command resolves a
repository root from --repo-root, else from the path in hand — the nearest ancestor holding
a managed docs/adr/INDEX.md, else the nearest holding .git — else from the working
directory. Only the `__main__` line reads the working directory; every function below takes
its root, so a test injects a fixture root and never changes directory.

The tool writes what it wholly owns: the index, a field with one right value given the
command, a filename, a heading number, a link target, its own fixed template, and text the
agent passed verbatim. It never rewrites a sentence the agent wrote.
"""

import argparse
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date
from pathlib import Path

# The floor the syntax here needs (`X | None` in evaluated annotations, dataclass slots).
# Checked rather than assumed: a consumer runs this on whatever python3 they have.
PYTHON_FLOOR = (3, 10)
if sys.version_info < PYTHON_FLOOR:
    sys.exit(f"adr.py needs Python {PYTHON_FLOOR[0]}.{PYTHON_FLOOR[1]} or newer")

from frontmatter import parse_frontmatter

ADR_DIR = Path("docs") / "adr"
INDEX_FILENAME = "INDEX.md"

# A byte-order mark opens a file some editors write; stripped on read, never on write.
BOM = "\ufeff"

# A fixed literal — no path, no version — so the hook, a pre-commit hook and `uvx` all
# generate the same bytes, and the first line doubles as the hooks' gate.
INDEX_HEADER_LINE = "<!-- Auto-generated by phx:writing-adrs — do not edit manually. -->"
INDEX_HEADER = f"{INDEX_HEADER_LINE}\n\n# ADR Index\n"
TABLE_HEADER = (
    "| # | Status | Title | Scope | Summary | Revisit |\n"
    "|---|--------|-------|-------|---------|---------|\n"
)
# An empty table reads as a file that was truncated. Say so instead.
EMPTY_NOTE = "_No decisions are recorded yet._\n"

STATUSES = ("Accepted", "Archived", "Superseded")
# Still in force, and so still checked and still surfaced to whoever edits a bound path.
# Superseded is neither: it is history, and "supersede, don't edit" means a stale path in
# one could not be fixed anyway.
BINDING_STATUSES = ("Accepted", "Archived")
# Kept out of the index an agent loads by default: Superseded because a later ADR replaced
# it, Archived because something other than a reader carries it.
HIDDEN_STATUSES = ("Archived", "Superseded")
# Frontmatter each status requires and the others refuse.
STATUS_FIELDS = {"Archived": "archived-because", "Superseded": "superseded-by"}

REVISIT_WHEN_FIELD = "revisit-when"
REVISIT_DISCHARGED_BY_FIELD = "revisit-discharged-by"
SCOPE_FIELD = "scope"
SUMMARY_FIELD = "summary"
SUPERSEDED_BY_FIELD = "superseded-by"
# Replaced by `scope`. Named so a stale field fails rather than being ignored.
TAGS_FIELD = "tags"

NUMBER_WIDTH = 3

RE_ADR_FILENAME = re.compile(r"^\d+-.*\.md$")
RE_FILE_NUMBER = re.compile(r"^(\d+)")
RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
RE_H1_TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
RE_NUMBER_PREFIX = re.compile(r"^(\d+):\s*")
RE_SLUG_JUNK = re.compile(r"[^a-z0-9]+")

# The skill's Format template, verbatim. A test in the skill's suite asserts the fenced
# block in SKILL.md equals this string, so the two cannot drift.
FORMAT_TEMPLATE = """---
status: Accepted
date: YYYY-MM-DD
scope: [path/to/directory/, path/to/file.py]
summary: One sentence describing what was decided (not why).
# plus revisit-when where a condition would reopen this, and archived-because or
# superseded-by where the status calls for one
---

# NNN: Title (Imperative Mood)

## Context

Why is this a problem? Why now? What forces are at play?

## Options

<!-- Optional: one paragraph naming any cost two or more options share, and setting it
     aside. Omit where they share none. -->

### Option 1: Do nothing

**Pros:** ...
**Cons:** ...
**Risks:** ...

### Option 2: [Chosen option] (Accepted)

**Pros:** ...
**Cons:** ...
**Risks:** ...

### Option 3: [Rejected alternative]

**Pros:** ...
**Cons:** ...
**Risks:** ...

## Decision

State the decision and summarise the key reasons.

## Consequences

What follows — positive and negative.

<!-- Reference-style link definitions, alphabetised by label, go here -->
"""


@dataclass(frozen=True)
class Finding:
    """One thing wrong with the corpus, keyed by the value that would have to change.

    The key is what identifies a finding across a rename or a renumber: the entry for a
    dangling scope, the bare number for a collision, the file for a malformed ADR, the
    index path for staleness. The ADR number rides along for display only. So a dangling
    entry keeps its identity when the ADR carrying it is renumbered, while a malformed
    file is keyed by name and becomes a new finding once the name changes.
    """

    kind: str
    value: str
    adr: str | None
    message: str

    @property
    def id(self) -> str:
        """The identity a hook remembers between events."""
        return f"{self.kind}:{self.value}"

    def to_json(self) -> dict:
        """The wire form `reconcile` prints."""
        return {"adr": self.adr, "id": self.id, "kind": self.kind, "message": self.message}


@dataclass(frozen=True)
class Row:
    """One decision as the index and the reverse lookup render it."""

    number: str
    filename: str
    status: str
    title: str
    scope: list[str]
    summary: str
    revisit: str


def read_document(path: Path) -> str:
    """The text of one ADR, normalised for the parser: no leading byte-order mark.

    An editor on Windows writes a mark before the opening `---`, and the parser then reads
    a file with no frontmatter block at all. Its CRLF endings need nothing: a text-mode
    read folds them before this function sees them, so a replacement here is unreachable.
    The file itself is left as it is; a command that writes one writes it whole.
    """
    return path.read_text(encoding="utf-8").removeprefix(BOM)


def parse_adr(content: str) -> tuple[dict, str, str | None, list[str]]:
    """Return (frontmatter, title, heading number, problems) for one ADR document.

    Every rule a document must satisfy to be an ADR is checked here, so no caller holds
    a different view of what makes an ADR valid than the function that parses one. The
    heading number is returned rather than checked: agreeing with the filename needs the
    filename, which this function is not given.
    """
    match = RE_FRONTMATTER.match(content)
    if not match:
        return {}, "", None, ["has no frontmatter block"]

    fields, problems = parse_frontmatter(match.group(1))

    title_match = RE_H1_TITLE.search(match.group(2))
    heading_number = None
    if title_match:
        heading = title_match.group(1).strip()
        number_match = RE_NUMBER_PREFIX.match(heading)
        if number_match:
            heading_number = number_match.group(1)
        title = RE_NUMBER_PREFIX.sub("", heading)
    else:
        title = ""
        problems.append("has no level-one title heading")

    status = fields.get("status")
    if status not in STATUSES:
        problems.append(f"has status {status!r}; expected one of {', '.join(STATUSES)}")
    for owner, field in STATUS_FIELDS.items():
        if status == owner and not fields.get(field):
            problems.append(f"is {owner} but declares no `{field}`")
        elif status != owner and fields.get(field):
            problems.append(f"declares `{field}` but its status is {status!r}, not {owner}")

    if fields.get(REVISIT_DISCHARGED_BY_FIELD) and not fields.get(REVISIT_WHEN_FIELD):
        problems.append(
            f"declares `{REVISIT_DISCHARGED_BY_FIELD}` but no `{REVISIT_WHEN_FIELD}` to spend"
        )

    if TAGS_FIELD in fields:
        problems.append(
            f"declares `{TAGS_FIELD}`, which `{SCOPE_FIELD}` replaced; name the paths the "
            "decision binds instead of the words someone might search for"
        )

    # Absent and empty are different answers, so the field is required and `[]` says the
    # decision binds no path.
    if SCOPE_FIELD not in fields:
        problems.append(
            f"declares no `{SCOPE_FIELD}`; list the paths it binds, or `[]` where it binds none"
        )
    elif not isinstance(fields[SCOPE_FIELD], list):
        problems.append(
            f"declares `{SCOPE_FIELD}` as a scalar; write it as an inline list, e.g. "
            f"`{SCOPE_FIELD}: [scripts/, CHANGELOG.md]`"
        )
    return fields, title, heading_number, problems


def scope_problems(entries: list[str], root: Path) -> list[tuple[str, str, str]]:
    """Return (kind, entry, message) per scope entry that is wrong on disk.

    A glob and a directory missing its slash are authoring faults ("malformed"); an entry
    naming nothing is rot after a move or delete ("dangling"), which a hook reports as
    something to act on rather than as a typo.
    """
    problems = []
    for entry in entries:
        if any(char in entry for char in "*?["):
            message = (
                f"scopes `{entry}`, which reads as a glob; scope takes exact paths and "
                "directory prefixes ending in `/`, nothing else"
            )
            problems.append(("malformed", entry, message))
            continue
        target = root / entry
        if not target.exists():
            message = (
                f"scopes `{entry}`, which nothing matches. If the code moved, update "
                "`scope`; if it is gone, ask whether the decision still binds anything, "
                "and revisit it"
            )
            problems.append(("dangling", entry, message))
        elif target.is_dir() and not entry.endswith("/"):
            message = f"scopes `{entry}`, a directory; write it as `{entry}/`"
            problems.append(("malformed", entry, message))
    return problems


def scope_matches(entry: str, path: str) -> bool:
    """Whether a scope entry covers a path: the file itself, or anything beneath it."""
    return path == entry or (entry.endswith("/") and path.startswith(entry))


def cell(value: str | list[str]) -> str:
    """Render a frontmatter value for a Markdown table cell, escaping pipes."""
    if isinstance(value, list):
        value = ", ".join(value)
    return value.replace("|", "\\|")


def is_managed(root: Path) -> bool:
    """Whether `root` holds a corpus this tool generated: the index opens with the header."""
    index_file = root / ADR_DIR / INDEX_FILENAME
    if not index_file.is_file():
        return False
    with index_file.open(encoding="utf-8") as handle:
        return handle.readline().rstrip("\n") == INDEX_HEADER_LINE


def resolve_root(start: Path, explicit: Path | None = None) -> Path:
    """Return the repository root for a path in hand.

    An explicit root wins. Otherwise walk up from `start`: the first managed corpus is the
    root, and the first `.git` is too — so the innermost corpus wins, a submodule is its own
    root, and `new` from a subdirectory of an unmanaged repository lands at its top. With
    nothing above, the start itself.
    """
    if explicit is not None:
        return explicit.resolve()
    start = start.resolve()
    directory = start if start.is_dir() else start.parent
    for candidate in (directory, *directory.parents):
        if is_managed(candidate) or (candidate / ".git").exists():
            return candidate
    return directory


def relative_to_root(path: str, root: Path) -> str | None:
    """Return `path` in the repo-relative form scope entries use, or None if outside `root`.

    A hook hands over absolute paths; left alone they match no scope entry, and a confident
    "nothing binds this" is worse than an error. Outside the root there is no answer, which
    None says.
    """
    candidate = Path(path)
    if not candidate.is_absolute():
        return path
    # Resolved, so a path reaching outside the root through a symlink binds nothing here.
    try:
        return candidate.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return None


def inspect(root: Path) -> tuple[list[Row], list[Finding]]:
    """Parse every ADR under `root`. Return the index rows and every finding.

    Rows exclude hidden statuses; findings cover every ADR still in force. A file with
    problems contributes no row, so the index never renders a decision it could not read.
    """
    adr_dir = root / ADR_DIR
    if not adr_dir.is_dir():
        return [], [
            Finding(
                "missing", ADR_DIR.as_posix(), None, f"{ADR_DIR.as_posix()}/ does not exist"
            )
        ]

    rows: list[Row] = []
    findings: list[Finding] = []
    # The first file seen to claim each number, so a second can name it. Keyed by value:
    # `ADR 1` names one decision however many zeros pad its filename.
    claimed: dict[int, str] = {}
    for path in sorted(adr_dir.iterdir()):
        if path.name.startswith(".") or path.name == INDEX_FILENAME:
            continue
        # Reported before the filename rule rather than after it: a directory named like
        # an ADR would otherwise be opened as one, and "rename it NNN-slug.md" is no
        # instruction for a directory whose name already reads that way.
        if path.is_dir():
            findings.append(
                Finding(
                    "misfiled",
                    path.name,
                    None,
                    f"{path.name} is a directory; move it elsewhere under docs/",
                )
            )
            continue
        if not RE_ADR_FILENAME.match(path.name):
            findings.append(
                Finding(
                    "misfiled",
                    path.name,
                    None,
                    f"{path.name} is neither an ADR nor {INDEX_FILENAME}; rename it "
                    "NNN-slug.md or move it elsewhere under docs/",
                )
            )
            continue

        number = RE_FILE_NUMBER.match(path.name).group(1)
        fields, title, heading_number, problems = parse_adr(read_document(path))
        scoped = []
        if not problems and fields["status"] in BINDING_STATUSES:
            scoped = scope_problems(fields[SCOPE_FIELD], root)
        if heading_number is not None and int(heading_number) != int(number):
            problems.append(
                f"is numbered {number} by its filename and {heading_number} by its heading; "
                "make them agree, since the index takes the number from one and the title "
                "from the other"
            )
        claimant = claimed.setdefault(int(number), path.name)
        if claimant != path.name:
            findings.append(
                Finding(
                    "collision",
                    str(int(number)),
                    number,
                    f"{path.name} shares its number with {claimant}; renumber whichever "
                    "number nothing cites yet, since a number already cited cannot move",
                )
            )
        for kind, entry, message in scoped:
            findings.append(Finding(kind, entry, number, f"{path.name} {message}"))
        if problems:
            findings.append(
                Finding("malformed", path.name, number, f"{path.name} " + "; ".join(problems))
            )
        if problems or scoped or claimant != path.name:
            continue
        if fields["status"] in HIDDEN_STATUSES:
            continue
        # A discharged trigger leaves the index the way a Superseded ADR does: spent.
        revisit = (
            ""
            if fields.get(REVISIT_DISCHARGED_BY_FIELD)
            else fields.get(REVISIT_WHEN_FIELD, "")
        )
        rows.append(
            Row(
                number=number,
                filename=path.name,
                status=fields["status"],
                title=title,
                scope=list(fields[SCOPE_FIELD]),
                summary=fields.get(SUMMARY_FIELD, ""),
                revisit=revisit,
            )
        )
    return rows, findings


def render_index(rows: list[Row]) -> str:
    """Render the whole index file for `rows`."""
    body = "".join(
        f"| [{row.number}]({row.filename}) | {cell(row.status)} | {cell(row.title)} "
        f"| {cell(row.scope)} | {cell(row.summary)} | {cell(row.revisit)} |\n"
        for row in rows
    )
    return f"{INDEX_HEADER}\n{TABLE_HEADER + body if rows else EMPTY_NOTE}"


def reconcile(root: Path, write: bool) -> list[Finding]:
    """Validate the corpus and, with `write`, regenerate the index when it validates.

    Without `write` a stale index is a finding. With it, the index is rewritten whenever
    every ADR validates and staleness is never reported; while any finding stands the
    index is left exactly as found.
    """
    rows, findings = inspect(root)
    if findings:
        return findings
    index_file = root / ADR_DIR / INDEX_FILENAME
    rendered = render_index(rows)
    current = index_file.read_text(encoding="utf-8") if index_file.exists() else None
    if current == rendered:
        return []
    if write:
        index_file.write_text(rendered, encoding="utf-8")
        return []
    index_path = (ADR_DIR / INDEX_FILENAME).as_posix()
    return [
        Finding(
            "stale-index",
            index_path,
            None,
            f"{index_path} is stale; run `adr.py index` to regenerate it",
        )
    ]


def binding(root: Path, paths: list[str]) -> list[Row]:
    """Return the decisions in force whose scope covers any of `paths`.

    This is the direction the index cannot serve: from the file in hand to the decisions
    binding it. Archived decisions are reported too — in force, out of the index, and met
    at the moment someone edits what they bind. A directory is matched with its trailing
    slash, since that is how scope names one.
    """
    subjects = []
    for path in paths:
        relative = relative_to_root(path, root)
        if relative is None:
            continue
        if (root / relative).is_dir() and not relative.endswith("/"):
            relative += "/"
        subjects.append(relative)
    if not subjects:
        return []

    adr_dir = root / ADR_DIR
    if not adr_dir.is_dir():
        return []
    matches = []
    for path in sorted(adr_dir.iterdir()):
        if path.name.startswith(".") or not RE_ADR_FILENAME.match(path.name):
            continue
        # A directory named like an ADR binds nothing; `inspect` is where it is reported.
        if path.is_dir():
            continue
        fields, title, _, problems = parse_adr(read_document(path))
        # A malformed ADR silently binds nothing, and this is the one place the lookup
        # speaks, so say so rather than skip.
        if problems:
            print(
                f"Warning: {path.name} could not be read, so it binds nothing here",
                file=sys.stderr,
            )
            continue
        if fields["status"] not in BINDING_STATUSES:
            continue
        if any(
            scope_matches(entry, subject)
            for entry in fields[SCOPE_FIELD]
            for subject in subjects
        ):
            matches.append(
                Row(
                    number=RE_FILE_NUMBER.match(path.name).group(1),
                    filename=path.name,
                    status=fields["status"],
                    title=title,
                    scope=list(fields[SCOPE_FIELD]),
                    summary=fields.get(SUMMARY_FIELD, ""),
                    revisit=(
                        ""
                        if fields.get(REVISIT_DISCHARGED_BY_FIELD)
                        else fields.get(REVISIT_WHEN_FIELD, "")
                    ),
                )
            )
    return matches


def print_findings(findings: list[Finding]) -> None:
    """Print findings one per line on stderr, for a person or a CI log."""
    for finding in findings:
        print(f"Error: {finding.message}", file=sys.stderr)
    if findings:
        print("Fix the errors above before committing.", file=sys.stderr)


def command_index(root: Path) -> int:
    """`index`: regenerate INDEX.md, leaving it untouched on any finding."""
    findings = reconcile(root, write=True)
    if findings:
        print_findings(findings)
        return 1
    rows, _ = inspect(root)
    print(f"Generated {(root / ADR_DIR / INDEX_FILENAME)} ({len(rows)} entries)")
    return 0


def command_check(root: Path) -> int:
    """`check`: every finding, staleness included, and never a write."""
    findings = reconcile(root, write=False)
    if findings:
        print_findings(findings)
        return 1
    rows, _ = inspect(root)
    print(f"{len(rows)} decisions indexed; scope and index are current")
    return 0


def command_for(root: Path, paths: list[str], cwd: Path) -> int:
    """`for`: the reverse lookup, one line per binding decision.

    A relative path is the caller's, so it resolves against `cwd` and not against the root:
    run from `src/`, `for db/models.py` means `src/db/models.py`. Passed through unchanged it
    would match no scope entry and report no decisions, which reads as "nothing binds this".
    """
    resolved = [path if Path(path).is_absolute() else str(cwd / path) for path in paths]
    for row in binding(root, resolved):
        print(
            f"{row.number} ({row.status}): {row.title} — {(ADR_DIR / row.filename).as_posix()}"
        )
    return 0


def command_reconcile(root: Path, write: bool) -> int:
    """`reconcile`: the hooks' command; findings as JSON on stdout, always exit 0."""
    import json

    findings = reconcile(root, write=write)
    print(json.dumps({"findings": [f.to_json() for f in findings], "root": str(root)}))
    return 0


def build_parser() -> argparse.ArgumentParser:
    """The command line."""
    parser = argparse.ArgumentParser(prog="adr.py", description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--repo-root", type=Path, help="act on this tree instead of resolving one"
    )
    commands = parser.add_subparsers(dest="command", required=True)

    new = commands.add_parser("new", help="scaffold the next ADR")
    new.add_argument("title")
    new.add_argument("--summary", required=True, help="what was decided, one sentence")
    scope = new.add_mutually_exclusive_group(required=True)
    scope.add_argument(
        "--scope", action="append", default=[], help="a path the decision binds; repeatable"
    )
    scope.add_argument("--no-scope", action="store_true", help="the decision binds no path")
    new.add_argument("--revisit-when", help="the condition that would reopen the decision")

    commands.add_parser("index", help="regenerate docs/adr/INDEX.md")
    commands.add_parser("check", help="validate without writing; exit 1 on any finding")
    lookup = commands.add_parser("for", help="the decisions binding these paths")
    lookup.add_argument("paths", nargs="+")
    supersede = commands.add_parser("supersede", help="mark OLD superseded by NEW")
    supersede.add_argument("old", type=int)
    supersede.add_argument("--by", dest="new", type=int, required=True)
    discharge = commands.add_parser(
        "discharge", help="record that NEW discharged OLD's trigger"
    )
    discharge.add_argument("old", type=int)
    discharge.add_argument("--by", dest="new", type=int, required=True)
    renumber = commands.add_parser(
        "renumber", help="move OLD to NEW and every citation in docs/adr"
    )
    renumber.add_argument("old", type=int)
    renumber.add_argument("new", type=int)
    rec = commands.add_parser(
        "reconcile", help="findings as JSON; --write regenerates a valid index"
    )
    rec.add_argument("--write", action="store_true")
    return parser


def main(argv: list[str], cwd: Path) -> int:
    """Run one command. `cwd` is the working directory the caller was given, never read here."""
    args = build_parser().parse_args(argv)
    root = resolve_root(cwd, args.repo_root)
    if args.command == "index":
        return command_index(root)
    if args.command == "check":
        return command_check(root)
    if args.command == "for":
        return command_for(root, args.paths, cwd)
    if args.command == "reconcile":
        return command_reconcile(root, args.write)
    if args.command == "new":
        return command_new(root, args)
    if args.command == "supersede":
        return command_edit(root, supersede, args.old, args.new)
    if args.command == "discharge":
        return command_edit(root, discharge, args.old, args.new)
    return command_renumber(root, args.old, args.new)


def cli() -> int:
    """Entry point for the phx-adr script."""
    return main(sys.argv[1:], Path.cwd())


class AdrError(Exception):
    """A command that cannot proceed; the message is for the person who ran it."""


def slugify(title: str) -> str:
    """Kebab-case a title for a filename."""
    return RE_SLUG_JUNK.sub("-", title.lower()).strip("-")


def next_number(adr_dir: Path) -> int:
    """One past the highest number on disk, or 1 for an empty corpus."""
    numbers = (
        [
            int(RE_FILE_NUMBER.match(p.name).group(1))
            for p in adr_dir.iterdir()
            if RE_ADR_FILENAME.match(p.name)
        ]
        if adr_dir.is_dir()
        else []
    )
    return max(numbers, default=0) + 1


def render_new(
    number: int,
    title: str,
    summary: str,
    scope: list[str],
    revisit_when: str | None,
    today: date,
) -> str:
    """The template with its frontmatter and heading filled; the body left for the agent."""
    frontmatter = [
        "status: Accepted",
        f"date: {today.isoformat()}",
        f"scope: [{', '.join(scope)}]",
        f"summary: {summary}",
    ]
    if revisit_when:
        frontmatter.append(f"revisit-when: {revisit_when}")
    _, body = FORMAT_TEMPLATE.split("---\n\n# NNN: Title (Imperative Mood)\n", 1)
    return (
        "---\n"
        + "\n".join(frontmatter)
        + f"\n---\n\n# {number:0{NUMBER_WIDTH}d}: {title}\n"
        + body
    )


def new_adr(
    root: Path,
    title: str,
    summary: str,
    scope: list[str],
    revisit_when: str | None,
    today: date,
) -> Path:
    """Scaffold the next ADR, creating the corpus on first use, and regenerate the index.

    The title, the values, the scope and the existing corpus are all checked before
    anything is written: a scope entry naming nothing is refused the way the index would
    refuse it, and a fault already on disk is refused before a new file could land beside
    it, index-less. A value the frontmatter cannot carry is refused for the same reason —
    written, it would fail the reconcile that follows and leave an ADR the index omits.
    """
    if not slugify(title):
        raise AdrError("title yields an empty slug")
    if "\n" in summary:
        raise AdrError("summary holds a line break; frontmatter carries a value on one line")
    for entry in scope:
        if "," in entry or "\n" in entry:
            raise AdrError(
                f"scope entry {entry!r} holds a comma or a line break, and the inline list "
                "would split it into entries naming nothing"
            )
    problems = scope_problems(scope, root)
    if problems:
        raise AdrError("; ".join(message for _, _, message in problems))
    adr_dir = root / ADR_DIR
    if adr_dir.is_dir():
        _, findings = inspect(root)
        if findings:
            raise AdrError("; ".join(f.message for f in findings))
    adr_dir.mkdir(parents=True, exist_ok=True)
    number = next_number(adr_dir)
    path = adr_dir / f"{number:0{NUMBER_WIDTH}d}-{slugify(title)}.md"
    path.write_text(
        render_new(number, title, summary, scope, revisit_when, today), encoding="utf-8"
    )
    findings = reconcile(root, write=True)
    if findings:
        raise AdrError("; ".join(f.message for f in findings))
    return path


def set_fields(content: str, updates: dict[str, str | None]) -> str:
    """Return `content` with frontmatter fields replaced, appended, or (given None) removed.

    Only the block between the markers changes; a field in place keeps its position and a
    new one goes last. The body is returned byte for byte.
    """
    match = RE_FRONTMATTER.match(content)
    if not match:
        raise AdrError("has no frontmatter block")
    lines = match.group(1).split("\n")
    for key, value in updates.items():
        prefix = f"{key}:"
        present = [i for i, line in enumerate(lines) if line.startswith(prefix)]
        if value is None:
            lines = [line for i, line in enumerate(lines) if i not in present]
        elif present:
            lines[present[0]] = f"{key}: {value}"
        else:
            lines.append(f"{key}: {value}")
    return "---\n" + "\n".join(lines) + "\n---\n" + match.group(2)


def find_adr(root: Path, number: int) -> Path:
    """The file carrying `number`, however its filename pads it."""
    adr_dir = root / ADR_DIR
    for path in sorted(adr_dir.iterdir()) if adr_dir.is_dir() else []:
        match = RE_FILE_NUMBER.match(path.name)
        if RE_ADR_FILENAME.match(path.name) and int(match.group(1)) == number:
            return path
    raise AdrError(f"no ADR is numbered {number}")


def regenerate_or_raise(root: Path) -> None:
    """Regenerate the index after an edit, raising the findings if it cannot."""
    findings = reconcile(root, write=True)
    if findings:
        raise AdrError("; ".join(f.message for f in findings))


def refuse_on_findings(root: Path) -> None:
    """Raise the corpus's findings, so a command refuses before it writes anything.

    A command that wrote first and then failed to regenerate left the edit on disk with
    the index behind it — a second fault to fix beside the one that was already there.
    Every command asks before its first write; `new` asks inline, having first to allow
    for a corpus that does not exist yet.
    """
    _, findings = inspect(root)
    if findings:
        raise AdrError("; ".join(f.message for f in findings))


def supersede(root: Path, old: int, new: int) -> None:
    """Mark `old` superseded by `new` and regenerate. The body is the agent's to edit."""
    path = find_adr(root, old)
    find_adr(root, new)
    refuse_on_findings(root)
    updated = set_fields(
        read_document(path), {"status": "Superseded", SUPERSEDED_BY_FIELD: str(new)}
    )
    path.write_text(updated, encoding="utf-8")
    regenerate_or_raise(root)


def discharge(root: Path, old: int, new: int) -> None:
    """Record that `new` spent `old`'s revisit trigger. Striking the body through is the agent's."""
    path = find_adr(root, old)
    find_adr(root, new)
    refuse_on_findings(root)
    content = read_document(path)
    fields, _, _, _ = parse_adr(content)
    if not fields.get(REVISIT_WHEN_FIELD):
        raise AdrError(f"ADR {old} has no {REVISIT_WHEN_FIELD} to spend")
    if fields.get("status") == "Superseded":
        raise AdrError(
            f"ADR {old} is Superseded; a discharge on it empties a cell nobody reads"
        )
    path.write_text(
        set_fields(content, {REVISIT_DISCHARGED_BY_FIELD: str(new)}), encoding="utf-8"
    )
    regenerate_or_raise(root)


def renumber(root: Path, old: int, new: int) -> list[str]:
    """Move `old` to `new` across docs/adr; return citations elsewhere for the agent.

    Rewrites the filename, the heading number, every `ADR <old>` citation and `<old>-slug`
    link target in the corpus, and the peer fields naming the number. Files outside
    docs/adr are searched, not edited: a code comment is the agent's to move.
    """
    path = find_adr(root, old)
    refuse_on_findings(root)
    adr_dir = root / ADR_DIR
    claimed = any(
        RE_ADR_FILENAME.match(p.name) and int(RE_FILE_NUMBER.match(p.name).group(1)) == new
        for p in adr_dir.iterdir()
    )
    if claimed:
        raise AdrError(f"ADR {new} already exists; pick a number nothing claims")
    new_padded = f"{new:0{NUMBER_WIDTH}d}"
    slug = path.name[len(RE_FILE_NUMBER.match(path.name).group(1)) :]
    re_citation = re.compile(rf"\bADR 0*{old}\b")
    re_link = re.compile(rf"\b0*{old}({re.escape(slug)})")
    re_heading = re.compile(rf"^# 0*{old}:", re.MULTILINE)

    for peer in sorted(adr_dir.iterdir()):
        if not RE_ADR_FILENAME.match(peer.name) or peer == path:
            continue
        text = read_document(peer)
        text = re_citation.sub(f"ADR {new_padded}", text)
        text = re_link.sub(rf"{new_padded}\1", text)
        peer_updates = {}
        peer_fields = parse_adr(text)[0]
        for field in (SUPERSEDED_BY_FIELD, REVISIT_DISCHARGED_BY_FIELD):
            if peer_fields.get(field) == str(old):
                peer_updates[field] = str(new)
        if peer_updates:
            text = set_fields(text, peer_updates)
        peer.write_text(text, encoding="utf-8")

    text = read_document(path)
    text = re_heading.sub(f"# {new_padded}:", text)
    target = adr_dir / f"{new_padded}{slug}"
    target.write_text(text, encoding="utf-8")
    path.unlink()
    regenerate_or_raise(root)
    return citations_outside_corpus(root, old, slug)


def citations_outside_corpus(root: Path, old: int, slug: str) -> list[str]:
    """`path:line: text` for every mention of the number outside docs/adr, for the agent."""
    import subprocess

    re_any = re.compile(rf"\bADR 0*{old}\b|\b0*{old}{re.escape(slug)}")
    try:
        listing = subprocess.run(
            ["git", "ls-files", "-co", "--exclude-standard"],
            capture_output=True,
            check=True,
            cwd=root,
            text=True,
        ).stdout.split("\n")
    except (OSError, subprocess.CalledProcessError):
        listing = [p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()]
    found = []
    for relative in listing:
        if not relative or relative.startswith(ADR_DIR.as_posix() + "/"):
            continue
        file = root / relative
        try:
            lines = file.read_text(encoding="utf-8").split("\n")
        except (OSError, UnicodeDecodeError):
            continue
        for index, line in enumerate(lines, start=1):
            if re_any.search(line):
                found.append(f"{relative}:{index}: {line}")
    return found


def command_new(root: Path, args: argparse.Namespace) -> int:
    """`new`: print the path written."""
    try:
        scope = [] if args.no_scope else args.scope
        today = date.today()  # noqa: DTZ011 — the local date, as the author writes it
        path = new_adr(root, args.title, args.summary, scope, args.revisit_when, today)
    except AdrError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    print(path)
    return 0


def command_edit(
    root: Path, action: Callable[[Path, int, int], None], old: int, new: int
) -> int:
    """`supersede` and `discharge` share one shape: act, or print the error."""
    try:
        action(root, old, new)
    except AdrError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


def command_renumber(root: Path, old: int, new: int) -> int:
    """`renumber`: move, then list what the agent still has to move by hand."""
    try:
        remaining = renumber(root, old, new)
    except AdrError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    if remaining:
        print("Citations outside docs/adr still name the old number; move each by hand:")
        for line in remaining:
            print(f"  {line}")
    return 0


if __name__ == "__main__":
    sys.exit(cli())
